# ═══════════════════════════════════════════════════════════════
# R8 PARITY — Python twin vs TypeScript reference (Supremacy Pack)
#
# Fixtures generated by scripts/r8-supremacy-fixtures.ts from the
# authoritative TS implementation. Proves:
#   1. canonical JSON is byte-identical across runtimes
#   2. the Merkle root is identical
#   3. inclusion proofs verify identically
#   4. tamper audit localizes the EXACT same slot/uid
#   5. native constitutional fuzz (P1/P3) on the Python machines
# ═══════════════════════════════════════════════════════════════

import json
import os

import pytest

from kernel.supremacy import (
    audit_evidence_bundle,
    build_merkle_tree,
    canonical_json,
    merkle_inclusion_proof,
    seal_evidence_bundle,
    sha256_canonical,
    verify_inclusion_proof,
    xorshift32,
)
from kernel.state_machines import ALL_MACHINES

FIXTURES = os.path.join(os.path.dirname(__file__), "fixtures", "supremacy", "merkle.json")
PARITY = os.path.join(os.path.dirname(__file__), "fixtures", "parity", "fixtures.json")


@pytest.fixture(scope="module")
def fx():
    with open(FIXTURES, "r", encoding="utf-8") as f:
        return json.load(f)


# ── 1. Canonical substrate parity ─────────────────────────────────

@pytest.mark.parametrize("case_index", [0, 1, 2])
def test_canonical_json_parity(fx, case_index):
    case = fx["canonical"][case_index]
    if "expected" in case:
        assert canonical_json(case["input"]) == case["expected"]
    else:
        assert sha256_canonical(case["input"]) == case["expectedSha256"]


# ── 2. Merkle root parity ─────────────────────────────────────────

def test_merkle_root_identical(fx):
    leaves = fx["merkle"]["leaves"]
    tree = build_merkle_tree(leaves)
    assert tree["root"] == fx["merkle"]["root"], "Python root diverges from TS reference"
    assert tree["leaf_count"] == fx["merkle"]["leafCount"]


def test_bundle_seal_parity(fx):
    records = [
        {"evidenceUid": uid, "contentHash": h}
        for uid, h in zip(fx["merkle"]["order"], fx["merkle"]["leaves"])
    ]
    bundle = seal_evidence_bundle(records, fx["meta"]["sealedAt"])
    assert bundle["root"] == fx["merkle"]["root"]
    assert bundle["sealHash"] == fx["merkle"]["sealHash"]


# ── 3. Inclusion proof parity ─────────────────────────────────────

@pytest.mark.parametrize("proof_index", [0, 1, 2])
def test_inclusion_proofs_parity(fx, proof_index):
    leaves = fx["merkle"]["leaves"]
    tree = build_merkle_tree(leaves)
    expected = fx["merkle"]["proofs"][proof_index]
    proof = merkle_inclusion_proof(tree, expected["index"])
    assert proof["leaf_hash"] == expected["leafHash"]
    assert [(s["hash"], s["direction"]) for s in proof["path"]] == [
        (s["hash"], s["direction"]) for s in expected["path"]
    ], "proof path differs from TS"
    assert verify_inclusion_proof(proof["leaf_hash"], proof, tree["root"]) is True
    assert expected["valid"] is True


# ── 4. Tamper audit parity (localization) ─────────────────────────

def test_audit_intact_parity(fx):
    records = [
        {"evidenceUid": uid, "contentHash": h}
        for uid, h in zip(fx["merkle"]["order"], fx["merkle"]["leaves"])
    ]
    bundle = seal_evidence_bundle(records, fx["meta"]["sealedAt"])
    audit = audit_evidence_bundle(records, bundle)
    assert audit["verdict"] == fx["merkle"]["auditIntact"]["verdict"] == "SEALED_INTACT"
    assert audit["anomalies"] == []


def test_audit_tamper_localization_parity(fx):
    slot = fx["merkle"]["tamperSlot"]
    records = [
        {"evidenceUid": uid, "contentHash": ("f" * 64 if i == slot else h)}
        for i, (uid, h) in enumerate(zip(fx["merkle"]["order"], fx["merkle"]["leaves"]))
    ]
    bundle = seal_evidence_bundle(
        [{"evidenceUid": uid, "contentHash": h} for uid, h in zip(fx["merkle"]["order"], fx["merkle"]["leaves"])],
        fx["meta"]["sealedAt"],
    )
    audit = audit_evidence_bundle(records, bundle)
    expected = fx["merkle"]["auditTamper"]
    assert audit["verdict"] == expected["verdict"] == "TAMPERED"
    ts_anomalies = [(a["type"], a["index"], a["evidenceUid"]) for a in expected["anomalies"]]
    py_anomalies = [(a["type"], a["index"], a["evidenceUid"]) for a in audit["anomalies"]]
    assert py_anomalies == ts_anomalies, "tamper localization differs across runtimes"


def test_bundle_metadata_tamper_detected(fx):
    records = [
        {"evidenceUid": uid, "contentHash": h}
        for uid, h in zip(fx["merkle"]["order"], fx["merkle"]["leaves"])
    ]
    bundle = seal_evidence_bundle(records, fx["meta"]["sealedAt"])
    forged = dict(bundle, leafCount=bundle["leafCount"] + 1)
    audit = audit_evidence_bundle(records, forged)
    assert any(a["type"] == "SEAL_MISMATCH" for a in audit["anomalies"])


# ── 5. Native constitutional fuzz (Python machines) ───────────────

def test_native_fuzz_illegal_rejections():
    """P3 on the Python kernel: no undeclared transition is ever accepted."""
    rnd = xorshift32(20260907)
    violations = []
    for it in range(3000):
        m = ALL_MACHINES[int(rnd() * len(ALL_MACHINES)) % len(ALL_MACHINES)]
        frm = m.states[int(rnd() * len(m.states)) % len(m.states)]
        to = m.states[int(rnd() * len(m.states)) % len(m.states)]
        declared = any(t.from_ == frm and t.to == to for t in m.transitions)
        accepted = any(t.from_ == frm and t.to == to for t in m.transitions)
        if not declared and accepted:
            violations.append((m.name, frm, to))
    assert violations == []


def test_native_fuzz_terminal_absorption():
    """P2 on the Python kernel: terminals have no outgoing transition."""
    for m in ALL_MACHINES:
        for t in m.terminal:
            assert not any(tr.from_ == t for tr in m.transitions), (
                f"{m.name}: terminal {t} has an outgoing transition — absorption broken"
            )


def test_xorshift32_matches_ts_semantics():
    """Same seed → same [0,1) sequence shape (monotone contract of the PRNG)."""
    rnd = xorshift32(42)
    seq = [rnd() for _ in range(4)]
    assert all(0.0 <= x < 1.0 for x in seq)
    assert len(set(seq)) == 4  # deterministic non-repeating early sequence
