# ═══════════════════════════════════════════════════════════════
# YAHRIA KERNEL (Python port) — Supremacy Pack twin (R8)
# Doc ID: YAHRIA-KRN-016-PY | Port of: src/lib/yahria/merkle-evidence.ts
#                                    + src/lib/yahria/canonical.ts
#
# Cross-runtime parity layer for the R8 Supremacy Pack. The Merkle
# algorithm hashes hex-string concatenations only, so both runtimes
# produce byte-identical roots, proofs, and audit reports. The
# canonical JSON substrate reuses the R7.1 JS-emulation layer.
#
# Verified against fixtures generated by scripts/r8-supremacy-fixtures.ts
# (tests/test_parity_supremacy.py).
# ═══════════════════════════════════════════════════════════════

import hashlib
import json
from typing import Any

from .canonical_json import js_stringify


# ── Canonical substrate (port of canonical.ts) ────────────────────

def canonical_json(value: Any) -> str:
    """Sorted-keys canonical JSON — mirrors canonical.ts serialize()."""
    if value is None or isinstance(value, bool):
        return "true" if value is True else "false" if value is False else "null"
    if isinstance(value, (int, float)):
        return js_stringify(value)
    if isinstance(value, str):
        return js_stringify(value)
    if isinstance(value, (list, tuple)):
        return "[" + ",".join(canonical_json(None if v is None else v) for v in value) + "]"
    if isinstance(value, dict):
        keys = sorted(k for k in value.keys() if value[k] is not None)
        return "{" + ",".join(
            json.dumps(k, ensure_ascii=False) + ":" + canonical_json(value[k])
            for k in keys
        ) + "}"
    return "null"


def sha256_hex(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def sha256_canonical(value: Any) -> str:
    return sha256_hex(canonical_json(value))


# ── Merkle tree (port of merkle-evidence.ts, ME-1..ME-4) ──────────

def build_merkle_tree(leaf_hashes: list[str]) -> dict:
    if not leaf_hashes:
        empty = sha256_hex("")
        return {"leaves": [], "levels": [[empty]], "root": empty, "leaf_count": 0}
    levels = [list(leaf_hashes)]
    current = levels[0]
    while len(current) > 1:
        nxt = []
        for i in range(0, len(current), 2):
            left = current[i]
            right = current[i + 1] if i + 1 < len(current) else current[i]
            nxt.append(sha256_hex(left + right))
        levels.append(nxt)
        current = nxt
    return {
        "leaves": list(leaf_hashes),
        "levels": levels,
        "root": current[0],
        "leaf_count": len(leaf_hashes),
    }


def merkle_inclusion_proof(tree: dict, index: int) -> dict:
    if index < 0 or index >= tree["leaf_count"]:
        raise IndexError(f"Leaf index {index} out of bounds (0..{tree['leaf_count'] - 1})")
    path = []
    i = index
    for level in range(len(tree["levels"]) - 1):
        nodes = tree["levels"][level]
        if i % 2 == 0:
            sibling = nodes[i + 1] if i + 1 < len(nodes) else nodes[i]
            direction = "R"
        else:
            sibling = nodes[i - 1]
            direction = "L"
        path.append({"hash": sibling, "direction": direction})
        i //= 2
    return {"index": index, "leaf_hash": tree["leaves"][index], "path": path, "root": tree["root"]}


def verify_inclusion_proof(leaf_hash: str, proof: dict, root: str) -> bool:
    if proof["root"] != root:
        return False
    acc = leaf_hash
    for step in proof["path"]:
        acc = sha256_hex(acc + step["hash"]) if step["direction"] == "R" else sha256_hex(step["hash"] + acc)
    return acc == root


def seal_evidence_bundle(records: list[dict], sealed_at: str) -> dict:
    if not records:
        raise ValueError("Refusing to seal an empty evidence bundle (INV-033)")
    order = [r["evidenceUid"] for r in records]
    leaf_hashes = [r["contentHash"] for r in records]
    tree = build_merkle_tree(leaf_hashes)
    root = tree["root"]
    seal_hash = sha256_hex(sha256_hex(root) + "|" + str(len(records)) + "|" + sealed_at)
    return {
        "root": root,
        "leafCount": len(records),
        "sealHash": seal_hash,
        "order": order,
        "leafHashes": leaf_hashes,
        "sealedAt": sealed_at,
    }


def audit_evidence_bundle(records: list[dict], bundle: dict) -> dict:
    anomalies = []
    by_uid = {r["evidenceUid"]: r for r in records}
    present = set(by_uid)

    recomputed_seal = sha256_hex(sha256_hex(bundle["root"]) + "|" + str(bundle["leafCount"]) + "|" + bundle["sealedAt"])
    if recomputed_seal != bundle["sealHash"]:
        anomalies.append({"type": "SEAL_MISMATCH", "index": None, "evidenceUid": "*",
                          "detail": "sealHash du faisceau invalide — métadonnées modifiées après scellement"})

    for i, uid in enumerate(bundle["order"]):
        if uid not in present:
            anomalies.append({"type": "MISSING", "index": i, "evidenceUid": uid,
                              "detail": f"preuve scellée au slot {i} absente — suppression détectée"})

    for r in records:
        if r["evidenceUid"] not in bundle["order"]:
            anomalies.append({"type": "EXTRA", "index": None, "evidenceUid": r["evidenceUid"],
                              "detail": "enregistrement jamais scellé — injection post-scellement détectée"})

    for i, uid in enumerate(bundle["order"]):
        rec = by_uid.get(uid)
        if rec is None:
            continue
        if rec["contentHash"] != bundle["leafHashes"][i]:
            anomalies.append({"type": "HASH_MISMATCH", "index": i, "evidenceUid": uid,
                              "detail": f"slot {i} : hash présenté ≠ hash scellé — contenu altéré"})

    intact = len(anomalies) == 0
    return {
        "intact": intact,
        "recomputedRoot": build_merkle_tree(bundle["leafHashes"])["root"],
        "anomalies": anomalies,
        "verdict": "SEALED_INTACT" if intact else "TAMPERED",
    }


# ── Seeded PRNG (xorshift32 — must match TS bit-for-bit) ──────────

def xorshift32(seed: int):
    s = seed & 0xFFFFFFFF
    if s == 0:
        s = 0x9E3779B9

    def rnd() -> float:
        nonlocal s
        s = (s ^ ((s << 13) & 0xFFFFFFFF)) & 0xFFFFFFFF
        s = s ^ (s >> 17)
        s = (s ^ ((s << 5) & 0xFFFFFFFF)) & 0xFFFFFFFF
        return s / 0x100000000

    return rnd
