// ═══════════════════════════════════════════════════════════════
// YAHRIA KERNEL — Global Invariants (INV-001 → INV-215)
// Doc ID: YAHRIA-KRN-002 | Source: GLOBAL_INVARIANTS.md V1.0.0 FROZEN
// ═══════════════════════════════════════════════════════════════

export interface Invariant {
  id: string;
  family: string;
  title: string;
  rule: string;
}

export const INVARIANTS: Invariant[] = [
  { id: 'INV-001', family: 'CORE', title: 'Architectural Integrity', rule: 'Every component MUST belong to a declared architectural domain. No undefined ownership.' },
  { id: 'INV-002', family: 'CORE', title: 'Single Responsibility Ownership', rule: 'Every critical responsibility MUST have one canonical owner.' },
  { id: 'INV-003', family: 'CORE', title: 'Explicit Dependencies', rule: 'Dependencies MUST be explicit. No hidden imports or implicit coupling.' },
  { id: 'INV-004', family: 'CORE', title: 'No Circular Dependencies', rule: 'The domain dependency graph MUST remain acyclic.' },
  { id: 'INV-010', family: 'IDENTITY', title: 'Explicit Identity', rule: 'Every security-relevant action MUST have an attributable identity.' },
  { id: 'INV-011', family: 'IDENTITY', title: 'Authentication Before Trust', rule: 'IDENTITY ≠ PERMISSION. Every privileged action requires explicit authorization.' },
  { id: 'INV-012', family: 'IDENTITY', title: 'Least Privilege', rule: 'Every actor receives only minimum required permissions.' },
  { id: 'INV-020', family: 'TENANCY', title: 'Tenant Isolation', rule: 'A tenant MUST NOT access another tenant data without authorized, auditable access.' },
  { id: 'INV-021', family: 'TENANCY', title: 'Explicit Tenant Context', rule: 'Tenant-scoped operations MUST have explicit tenant context.' },
  { id: 'INV-022', family: 'TENANCY', title: 'Organization Ownership', rule: 'Resource → Project → Organization → Tenant lineage MUST remain traceable.' },
  { id: 'INV-030', family: 'DATA', title: 'Data Integrity', rule: 'Persistent data MUST preserve identity, consistency, referential integrity, ownership.' },
  { id: 'INV-031', family: 'DATA', title: 'Explicit Persistence Contracts', rule: 'PK / FK / UNIQUE / CHECK / INDEX / RELATIONSHIP / LIFECYCLE must be declared.' },
  { id: 'INV-032', family: 'DATA', title: 'No Silent Schema Mutation', rule: 'Every structural change requires SPEC → MODEL → MIGRATION → TEST → VALIDATION.' },
  { id: 'INV-033', family: 'DATA', title: 'Immutable Evidence', rule: 'Sealed evidence MUST NOT be modified; corrections create new versions.' },
  { id: 'INV-034', family: 'DATA', title: 'Data Lineage', rule: 'SOURCE → TRANSFORMATION → DECISION → OUTPUT must remain traceable.' },
  { id: 'INV-040', family: 'EXECUTION', title: 'Explicit Execution Context', rule: 'Every execution MUST have execution_id, task_id, actor, tenant, policy_context.' },
  { id: 'INV-041', family: 'EXECUTION', title: 'No Uncontrolled Execution', rule: 'Untrusted or generated code MUST NOT execute outside approved runtime boundaries.' },
  { id: 'INV-042', family: 'EXECUTION', title: 'Resource Bounding', rule: 'Executions MUST be bounded by CPU, MEMORY, DISK, PID, TIMEOUT.' },
  { id: 'INV-043', family: 'EXECUTION', title: 'Cancellation and Termination', rule: 'Long executions MUST support controlled termination preserving evidence.' },
  { id: 'INV-044', family: 'EXECUTION', title: 'Failure Is Explicit', rule: 'UNKNOWN ≠ SUCCESS. Never convert unknown state into success.' },
  { id: 'INV-050', family: 'SANDBOX', title: 'Host Protection', rule: 'Host MUST remain protected from unauthorized FS, process, network, secret access.' },
  { id: 'INV-051', family: 'SANDBOX', title: 'Explicit Isolation', rule: 'FILESYSTEM / NETWORK / PROCESS / RESOURCE / IDENTITY boundaries MUST be explicit.' },
  { id: 'INV-052', family: 'SANDBOX', title: 'Default Deny', rule: 'Sandbox privileges: DENY BY DEFAULT, explicitly granted only.' },
  { id: 'INV-053', family: 'SANDBOX', title: 'No Secret Leakage', rule: 'Sandboxed execution MUST NOT receive credentials or production secrets.' },
  { id: 'INV-060', family: 'TOOL', title: 'Tool Identity', rule: 'Every registered tool MUST have tool_id, name, version, capabilities, contract.' },
  { id: 'INV-061', family: 'TOOL', title: 'Contract Validation', rule: 'Tool input/output MUST be validated against declared contracts.' },
  { id: 'INV-062', family: 'TOOL', title: 'Tool Authorization', rule: 'REGISTERED ≠ AUTHORIZED. Capability + policy evaluation before execution.' },
  { id: 'INV-063', family: 'TOOL', title: 'Tool Version Traceability', rule: 'Reproducibility MUST NOT depend on unspecified "latest".' },
  { id: 'INV-070', family: 'AGENT', title: 'Agent Identity', rule: 'Every autonomous agent MUST have explicit identity.' },
  { id: 'INV-071', family: 'AGENT', title: 'Capability Boundaries', rule: 'INTENT → CAPABILITY CHECK → POLICY CHECK → EXECUTION.' },
  { id: 'INV-072', family: 'AGENT', title: 'Agent Accountability', rule: 'Significant actions attributable to responsible agent identity.' },
  { id: 'INV-073', family: 'AGENT', title: 'Autonomy Is Governed', rule: 'AUTONOMY < POLICY. Autonomy never overrides governance.' },
  { id: 'INV-080', family: 'COGNITIVE', title: 'Model Output Is Not Fact', rule: 'MODEL OUTPUT → VERIFICATION → EVIDENCE → TRUST LEVEL.' },
  { id: 'INV-081', family: 'COGNITIVE', title: 'Uncertainty Must Be Representable', rule: 'VERIFIED / PROBABLE / UNCERTAIN / UNKNOWN / FALSE — unknown never becomes certain.' },
  { id: 'INV-082', family: 'COGNITIVE', title: 'Decisions Require Context', rule: 'Significant cognitive decisions preserve decision context.' },
  { id: 'INV-090', family: 'TASK', title: 'Explicit Task State', rule: 'Tasks MUST have explicit lifecycle states with controlled transitions.' },
  { id: 'INV-091', family: 'TASK', title: 'Task Dependency Integrity', rule: 'Task MUST NOT execute before mandatory dependencies are satisfied.' },
  { id: 'INV-092', family: 'TASK', title: 'Retry Is Governed', rule: 'Retries MUST have policy, max attempts, backoff, termination rule.' },
  { id: 'INV-100', family: 'OBSERVABILITY', title: 'Observability By Design', rule: 'Critical execution paths MUST emit EVENTS, TRACES, METRICS, LOGS.' },
  { id: 'INV-101', family: 'OBSERVABILITY', title: 'Correlation', rule: 'Related operations correlatable via trace_id, execution_id, task_id, agent_id.' },
  { id: 'INV-102', family: 'OBSERVABILITY', title: 'Evidence Before Assertion', rule: 'Assertion without evidence has lower trust than assertion + verifiable evidence.' },
  { id: 'INV-110', family: 'EVIDENCE', title: 'Evidence Integrity', rule: 'Evidence lifecycle: capture, identity, storage, integrity, lineage, retention.' },
  { id: 'INV-111', family: 'EVIDENCE', title: 'Evidence Traceability', rule: 'Critical evidence linked to the action that produced it.' },
  { id: 'INV-112', family: 'EVIDENCE', title: 'Replay Where Possible', rule: 'Critical executions SHOULD preserve replay information.' },
  { id: 'INV-120', family: 'POLICY', title: 'Policy Precedence', rule: 'POLICY DENY > MODEL > AGENT > TOOL > LOCAL IMPLEMENTATION.' },
  { id: 'INV-121', family: 'POLICY', title: 'Policy Is Explicit', rule: 'Security policy MUST be explicit, versioned, auditable.' },
  { id: 'INV-122', family: 'POLICY', title: 'Policy Version Traceability', rule: 'Critical actions record the applicable policy version.' },
  { id: 'INV-123', family: 'POLICY', title: 'Policy Explainability', rule: 'Decisions explainable through rule, condition, context, decision.' },
  { id: 'INV-130', family: 'SECURITY', title: 'Zero Trust', rule: 'No internal component is automatically trusted.' },
  { id: 'INV-131', family: 'SECURITY', title: 'Defense In Depth', rule: 'Critical protection MUST NOT depend on a single control.' },
  { id: 'INV-132', family: 'SECURITY', title: 'Secret Minimization', rule: 'Logs, traces, errors avoid secret disclosure.' },
  { id: 'INV-133', family: 'SECURITY', title: 'Security Failure Is Not Success', rule: 'UNKNOWN authorization → DENY.' },
  { id: 'INV-140', family: 'MEMORY', title: 'Memory Is Not Automatic Truth', rule: 'Memory carries source, confidence, timestamp, scope, validation state.' },
  { id: 'INV-141', family: 'MEMORY', title: 'Memory Has Governance', rule: 'Memory creation, consolidation, retrieval, deletion follow governance.' },
  { id: 'INV-142', family: 'MEMORY', title: 'Memory Lineage', rule: 'Important memory preserves its origin.' },
  { id: 'INV-150', family: 'LEARNING', title: 'Learning Requires Evidence', rule: 'Improvement NOT promoted because a model claims it is better.' },
  { id: 'INV-151', family: 'LEARNING', title: 'Learning Is Reversible', rule: 'Promoted improvements support rollback.' },
  { id: 'INV-152', family: 'LEARNING', title: 'Failure Is Learning Input', rule: 'Validated failures preserved as structured learning signals.' },
  { id: 'INV-160', family: 'EVOLUTION', title: 'No Unverified Self-Modification', rule: 'No autonomous promotion of critical self-modifications without verification.' },
  { id: 'INV-161', family: 'EVOLUTION', title: 'Separation Of Proposal And Approval', rule: 'The proposer MUST NOT be the sole approval authority.' },
  { id: 'INV-162', family: 'EVOLUTION', title: 'Experiment Before Promotion', rule: 'PROPOSAL → EXPERIMENT → BENCHMARK → VERIFY → POLICY → APPROVE → CANARY → PROMOTE.' },
  { id: 'INV-163', family: 'EVOLUTION', title: 'Rollback Capability', rule: 'Critical promoted changes MUST have rollback strategy.' },
  { id: 'INV-170', family: 'QUALITY', title: 'Testable Architecture', rule: 'Critical logic MUST NOT hide behind untestable global state.' },
  { id: 'INV-171', family: 'QUALITY', title: 'Compilation Is Not Validation', rule: 'Compilation success proves neither correctness nor security.' },
  { id: 'INV-172', family: 'QUALITY', title: 'Regression Protection', rule: 'Validated capability MUST NOT silently regress.' },
  { id: 'INV-180', family: 'CHANGE', title: 'No Silent Architectural Change', rule: 'Architectural changes MUST be explicit and versioned.' },
  { id: 'INV-181', family: 'CHANGE', title: 'Impact Analysis', rule: 'Critical changes consider dependencies, security, policy, data, rollback.' },
  { id: 'INV-182', family: 'CHANGE', title: 'Backward Compatibility', rule: 'Breaking changes MUST be explicit with migration paths.' },
  { id: 'INV-190', family: 'REPRODUCIBILITY', title: 'Versioned Execution', rule: 'Critical executions identify software, config, tool, policy, environment versions.' },
  { id: 'INV-191', family: 'REPRODUCIBILITY', title: 'Deterministic Control', rule: 'Non-determinism MUST be explicitly recognized.' },
  { id: 'INV-200', family: 'OVERSIGHT', title: 'Human Override', rule: 'Humans retain pause / cancel / approve / reject / rollback authority.' },
  { id: 'INV-201', family: 'OVERSIGHT', title: 'Explicit Override', rule: 'Human overrides attributable and auditable.' },
  { id: 'INV-210', family: 'FAILURE', title: 'Fail Safely', rule: 'DO NOT GUESS. DO NOT ESCALATE PRIVILEGE. DO NOT ASSUME SUCCESS.' },
  { id: 'INV-211', family: 'FAILURE', title: 'Failure Preserves Evidence', rule: 'Failure MUST NOT automatically erase evidence.' },
  { id: 'INV-212', family: 'OVERSIGHT', title: 'Single LLM Route', rule: 'Every LLM call routes through the fabric: declared providers, ordered fallback, visible attempts trace — no ad-hoc provider imports.' },
  { id: 'INV-213', family: 'SECURITY', title: 'Credentials Never Exposed', rule: 'Provider API keys stay server-side; telemetry exposes masked keys only.' },
  { id: 'INV-214', family: 'EXECUTION', title: 'Polyglot Proof Parity', rule: 'Every requested stack — including C, C++, C#, Fortran — goes through the SAME sandbox proof gates (build + run + output marker); no language is second-class, no stack ships unverified.' },
  { id: 'INV-215', family: 'SECURITY', title: 'Container Isolation When Docker', rule: 'When YAHRIA_SANDBOX_BACKEND=docker, every sandbox step runs in a hardened container: no network, read-only rootfs, all capabilities dropped, cpu/memory/pids bounded. The process backend remains an honestly documented weaker isolation.' },
];

export const INVARIANT_FAMILIES = Array.from(new Set(INVARIANTS.map((i) => i.family)));
