# -*- coding: utf-8 -*-
"""Audit technique de completude YAHRIA OS & RUN-000019 — corps du PDF (ReportLab)."""
import os
import sys
import hashlib

SKILL_SCRIPTS = "/home/z/my-project/skills/pdf/scripts"
if SKILL_SCRIPTS not in sys.path:
    sys.path.insert(0, SKILL_SCRIPTS)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, PageBreak,
                                Table, TableStyle, KeepTogether, CondPageBreak,
                                HRFlowable, Image)
from reportlab.platypus.tableofcontents import TableOfContents

import audit_contenu as C

# Typographie française : espace insécable avant tiret cadratin pour empêcher
# « — » de débuter une ligne (règle de ponctuation CJK/Latine du QA).
def _bind_fr(obj):
    if isinstance(obj, str):
        return obj.replace(' — ', '\u00a0— ')
    if isinstance(obj, list):
        return [_bind_fr(x) for x in obj]
    if isinstance(obj, tuple):
        return tuple(_bind_fr(x) for x in obj)
    return obj

for _k in [k for k in dir(C) if not k.startswith('_')]:
    setattr(C, _k, _bind_fr(getattr(C, _k)))

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#eff0f1')
SECTION_BG    = colors.HexColor('#f0f1f2')
CARD_BG       = colors.HexColor('#e4e7e8')
TABLE_STRIPE  = colors.HexColor('#ebedee')
HEADER_FILL   = colors.HexColor('#334650')
COVER_BLOCK   = colors.HexColor('#5a7886')
BORDER        = colors.HexColor('#b8c8cf')
ICON          = colors.HexColor('#52798c')
ACCENT        = colors.HexColor('#3681a6')
ACCENT_2      = colors.HexColor('#b43a4e')
TEXT_PRIMARY  = colors.HexColor('#1a1b1c')
TEXT_MUTED    = colors.HexColor('#6f7578')
SEM_SUCCESS   = colors.HexColor('#46875c')
SEM_WARNING   = colors.HexColor('#a18347')
SEM_ERROR     = colors.HexColor('#92453e')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_ROW_EVEN = colors.white
TABLE_ROW_ODD = TABLE_STRIPE

# ── Fonts ─────────────────────────────────────────────────────────────────────
FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
# NotoSansSC n'existe ici qu'en police variable (non chargeable par ReportLab) :
# alias défensif vers NotoSerifSC pour la chaîne de fallback (document 100 % latin).
pdfmetrics.registerFont(TTFont('Noto Sans SC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('Noto Sans SC Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('SarasaMonoSC', f'{FONT_DIR}/truetype/chinese/SarasaMonoSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))

registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('Noto Sans SC', normal='Noto Sans SC', bold='Noto Sans SC Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

from pdf import install_font_fallback
install_font_fallback()

# ── Layout constants ──────────────────────────────────────────────────────────
MARGIN = 0.9 * inch
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN
H1_COND = AVAIL_H * 0.25
H2_COND = AVAIL_H * 0.15
MAX_KEEP_HEIGHT = PAGE_H * 0.4

OUT = "/home/z/my-project/scripts/audit_body.pdf"

# ── Styles ────────────────────────────────────────────────────────────────────
body = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5, leading=17,
                      alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY,
                      spaceBefore=0, spaceAfter=9)
bullet = ParagraphStyle('Bullet', parent=body, alignment=TA_LEFT, leftIndent=16,
                        firstLineIndent=0, spaceAfter=6)
h1s = ParagraphStyle('H1', fontName='FreeSerif', fontSize=22, leading=27,
                     textColor=HEADER_FILL, spaceBefore=18, spaceAfter=4)
h2s = ParagraphStyle('H2', fontName='FreeSerif', fontSize=15, leading=20,
                     textColor=TEXT_PRIMARY, spaceBefore=16, spaceAfter=8)
h3s = ParagraphStyle('H3', fontName='FreeSerif', fontSize=11.5, leading=16,
                     textColor=TEXT_PRIMARY, spaceBefore=12, spaceAfter=6)
caption = ParagraphStyle('Caption', fontName='FreeSerif', fontSize=8.5, leading=12,
                         alignment=TA_CENTER, textColor=TEXT_MUTED,
                         spaceBefore=3, spaceAfter=6)
toc_title_style = ParagraphStyle('TocTitle', parent=h1s, spaceBefore=0)
toc_l0 = ParagraphStyle('TOC0', fontName='FreeSerif', fontSize=12, leading=20,
                        leftIndent=20, textColor=TEXT_PRIMARY)
toc_l1 = ParagraphStyle('TOC1', fontName='FreeSerif', fontSize=10.5, leading=16,
                        leftIndent=40, textColor=TEXT_MUTED)
th_style = ParagraphStyle('TH', fontName='FreeSerif', fontSize=9.5, leading=13,
                          textColor=colors.white, alignment=TA_LEFT)
td_style = ParagraphStyle('TD', fontName='FreeSerif', fontSize=9, leading=13,
                          textColor=TEXT_PRIMARY, alignment=TA_LEFT)
td_center = ParagraphStyle('TDC', parent=td_style, alignment=TA_CENTER)
stat_big = ParagraphStyle('StatBig', fontName='FreeSerif', fontSize=20, leading=24,
                          textColor=ACCENT, alignment=TA_CENTER)
stat_label = ParagraphStyle('StatLabel', fontName='FreeSerif', fontSize=8, leading=11,
                            textColor=TEXT_MUTED, alignment=TA_CENTER)

# ── TOC-aware doc template ────────────────────────────────────────────────────
FRONT_MATTER_PAGES = 1  # la page TOC

class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            # Numérotation affichée : la page TOC est « i », le corps repart à 1
            display_page = self.page - FRONT_MATTER_PAGES
            self.notify('TOCEntry', (level, text, display_page, key))

def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

def safe_keep_together(elements):
    total_h = 0
    for el in elements:
        try:
            w, h = el.wrap(AVAIL_W, PAGE_H)
        except Exception:
            h = 0
        total_h += h
    if total_h <= MAX_KEEP_HEIGHT:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)

def h1_block(text, first_flowables=None):
    """H1 + règle accent, protégé contre l'orphelinat."""
    head = add_heading(text, h1s, level=0)
    rule = HRFlowable(width='100%', thickness=1.5, color=ACCENT,
                      spaceBefore=2, spaceAfter=12)
    group = [head, rule]
    if first_flowables:
        group += first_flowables
    return [CondPageBreak(H1_COND)] + safe_keep_together(group)

def h2_block(text, first_flowables=None):
    head = add_heading(text, h2s, level=1)
    group = [head] + (first_flowables or [])
    return [CondPageBreak(H2_COND)] + safe_keep_together(group)

def make_table(data, ratios, header=True, center_cols=(), status_col=None):
    """Table standard : cellules Paragraph, largeur contrainte, rayures, centrée."""
    col_widths = [r * AVAIL_W for r in ratios]
    assert abs(sum(col_widths) - AVAIL_W) < 1.0, 'table width mismatch'
    wrapped = []
    for ri, row in enumerate(data):
        out_row = []
        for ci, cell in enumerate(row):
            if ri == 0 and header:
                out_row.append(Paragraph('<b>%s</b>' % cell, th_style))
            else:
                style = td_center if ci in center_cols else td_style
                if status_col is not None and ci == status_col:
                    color = {'FERMÉ': '#46875c', 'PACKAGÉ': '#a18347',
                             'OUVERT': '#92453e'}.get(cell, '#1a1b1c')
                    out_row.append(Paragraph('<font color="%s"><b>%s</b></font>'
                                             % (color, cell), td_center))
                else:
                    out_row.append(Paragraph(cell, style))
        wrapped.append(out_row)
    t = Table(wrapped, colWidths=col_widths, hAlign='CENTER', repeatRows=1)
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 7),
        ('RIGHTPADDING', (0, 0), (-1, -1), 7),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for ri in range(1, len(data)):
        style_cmds.append(('BACKGROUND', (0, ri), (-1, ri),
                           TABLE_ROW_ODD if ri % 2 else TABLE_ROW_EVEN))
    t.setStyle(TableStyle(style_cmds))
    return t

def add_table_block(story, data, ratios, cap, **kw):
    story.append(Spacer(1, 12))
    tbl = make_table(data, ratios, **kw)
    if len(data) <= 9:
        story.extend(safe_keep_together([tbl, Spacer(1, 6), Paragraph(cap, caption)]))
    else:
        story.append(tbl)
        story.append(Spacer(1, 6))
        story.append(Paragraph(cap, caption))
    story.append(Spacer(1, 12))

def metrics_row(metrics):
    n = len(metrics)
    cells = []
    for value, label in metrics:
        cells.append([Paragraph('<b>%s</b>' % value, stat_big),
                      Paragraph(label, stat_label)])
    t = Table([cells], colWidths=[AVAIL_W / n] * n, hAlign='CENTER')
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('BOX', (0, 0), (-1, -1), 1, ACCENT),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    return t

# ── Header / footer ───────────────────────────────────────────────────────────
DOC_TITLE = C.TITLE

def on_page(canvas, doc):
    canvas.saveState()
    # En-tête : titre + règle accent
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.55 * inch, DOC_TITLE)
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.62 * inch, PAGE_W - MARGIN, PAGE_H - 0.62 * inch)
    # Pied de page : règle légère + auteur + numéro
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 0.45 * inch, 'YAHRIA Code OS · Audit interne')
    page_label = 'i' if doc.page <= FRONT_MATTER_PAGES else str(doc.page - FRONT_MATTER_PAGES)
    canvas.drawRightString(PAGE_W - MARGIN, 0.45 * inch, page_label)
    canvas.restoreState()

# ── Chart (matplotlib) ────────────────────────────────────────────────────────
def build_chart(path):
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    from matplotlib.patches import Patch

    suites = [
        ("Parité Python (pytest)", 72, '#3681a6'),
        ("Suite R14 — domaines avancés", 47, '#3681a6'),
        ("Suite R13 — domaines précoces", 46, '#3681a6'),
        ("RUN-000019 · tests Jest", 40, '#b43a4e'),
        ("RUN-000019 · vérifications curl", 25, '#b43a4e'),
        ("Suite R12 — contrats et outils", 22, '#3681a6'),
        ("Suite r15 — VPS-ready", 16, '#3681a6'),
        ("CI constitutionnelle (12 pas)", 12, '#3681a6'),
    ]
    labels = [s[0] for s in suites][::-1]
    values = [s[1] for s in suites][::-1]
    bar_colors = [s[2] for s in suites][::-1]

    fig, ax = plt.subplots(figsize=(7.4, 3.5), dpi=200, constrained_layout=True)
    bars = ax.barh(labels, values, color=bar_colors, edgecolor='none', height=0.62)
    for rect, v in zip(bars, values):
        ax.text(v + 1.2, rect.get_y() + rect.get_height() / 2, str(v),
                va='center', ha='left', fontsize=10, color='#1a1b1c')
    ax.set_xlim(0, 80)
    ax.set_xticks([])
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['bottom'].set_visible(False)
    ax.spines['left'].set_color('#b8c8cf')
    ax.tick_params(axis='y', length=0, labelsize=10, colors='#1a1b1c')
    handles = [Patch(color='#3681a6', label='Plateforme YAHRIA OS'),
               Patch(color='#b43a4e', label='Livrable RUN-000019')]
    ax.legend(handles=handles, loc='lower left', bbox_to_anchor=(0, 1.02),
              ncol=2, frameon=False, fontsize=10)
    fig.savefig(path)
    plt.close(fig)

CHART_PNG = '/home/z/my-project/scripts/audit_chart.png'
build_chart(CHART_PNG)

def embed_image(path, max_width, max_height):
    from PIL import Image as PILImage
    pil = PILImage.open(path)
    ow, oh = pil.size
    ratio = min(max_width / ow if ow > max_width else 1.0,
                max_height / oh if oh > max_height else 1.0)
    return Image(path, width=ow * ratio, height=oh * ratio)

# ── Story ─────────────────────────────────────────────────────────────────────
story = []

# Table des matières (front matter, page « i »)
toc = TableOfContents()
toc.levelStyles = [toc_l0, toc_l1]
story.append(Paragraph('<b>Table des matières</b>', toc_title_style))
story.append(HRFlowable(width='100%', thickness=1.5, color=ACCENT, spaceBefore=2, spaceAfter=14))
story.append(toc)
story.append(PageBreak())

# ── 1. Synthèse exécutive ────────────────────────────────────────────────────
story += h1_block('1. Synthèse exécutive', [Paragraph(C.CH1_P1, body)])
story.append(Paragraph(C.CH1_P2, body))
story.append(Paragraph(C.CH1_P3, body))
story.append(Spacer(1, 10))
story.extend(safe_keep_together([metrics_row(C.METRICS), Spacer(1, 6),
                                 Paragraph('Indicateurs clés mesurés à la date de l\'audit', caption)]))
story.append(Spacer(1, 10))
story.append(Paragraph(C.CH1_P4, body))

# ── 2. Périmètre et méthodologie ─────────────────────────────────────────────
story += h1_block('2. Périmètre et méthodologie')
story += h2_block('2.1 Objet et sources de preuve', [Paragraph(C.CH2_1_P1, body)])
story.append(Paragraph(C.CH2_1_P2, body))
add_table_block(story, C.SOURCES_TABLE, [0.28, 0.28, 0.44],
                'Tableau 1 — Sources de preuve de l\'audit')
story += h2_block('2.2 Méthode d\'audit et frontières', [Paragraph(C.CH2_2_P1, body)])
story.append(Paragraph(C.CH2_2_P2, body))

# ── 3. Complétude plateforme ─────────────────────────────────────────────────
story += h1_block('3. Complétude de la plateforme YAHRIA OS')
story += h2_block('3.1 Couverture fonctionnelle : 24 domaines', [Paragraph(C.CH3_1_P1, body)])
add_table_block(story, C.DOMAINS_TABLE, [0.20, 0.22, 0.58],
                'Tableau 2 — Domaines majeurs : modules et preuves caractéristiques')
story.append(Paragraph(C.CH3_1_P2, body))
story += h2_block('3.2 Garde-fous constitutionnels', [Paragraph(C.CH3_2_P1, body)])
story.append(Paragraph(C.CH3_2_P2, body))
story += h2_block('3.3 Validation continue et suites de preuve', [Paragraph(C.CH3_3_P1, body)])
story.append(Paragraph(C.CH3_3_P2, body))
story.append(Spacer(1, 18))
chart_img = embed_image(CHART_PNG, AVAIL_W, 250)
story.extend(safe_keep_together([chart_img, Spacer(1, 8), Paragraph(C.CHART_CAPTION, caption)]))
story.append(Spacer(1, 18))
story += h2_block('3.4 Boucle autonome prouvée', [Paragraph(C.CH3_4_P1, body)])
add_table_block(story, C.MISSIONS_TABLE, [0.13, 0.34, 0.32, 0.21],
                'Tableau 3 — Missions YAHRIA exécutées avec traces scellées')
story += h2_block('3.5 API v1 et gouvernance d\'accès', [Paragraph(C.CH3_5_P1, body)])

# ── 4. Livrable RUN-000019 ───────────────────────────────────────────────────
story += h1_block('4. Complétude du livrable RUN-000019')
story += h2_block('4.1 Contexte et verdict initial', [Paragraph(C.CH4_1_P1, body)])
story += h2_block('4.2 Les six défauts structurels', [])
story.append(Paragraph('Le tableau suivant résume chaque défaut, tel que prouvé par exécution, avant correction.', body))
add_table_block(story, C.DEFECTS_TABLE, [0.06, 0.47, 0.47],
                'Tableau 4 — Défauts diagnostiqués sur le livrable initial', center_cols=(0,))
story += h2_block('4.3 Corrections structurelles', [Paragraph(C.CH4_3_P1, body)])
story.append(Paragraph(C.CH4_3_P2, body))
story += h2_block('4.4 Preuves d\'exécution', [Paragraph(C.CH4_4_P1, body)])
story.append(Spacer(1, 10))
story.extend(safe_keep_together([metrics_row(C.PROOF_METRICS), Spacer(1, 6),
                                 Paragraph('Preuves du livrable corrigé — jest et exécution live', caption)]))
story.append(Spacer(1, 10))

# ── 5. Matrice prod-ready ────────────────────────────────────────────────────
story += h1_block('5. Matrice prod-ready : six bloqueurs tracés', [Paragraph(C.CH5_P1, body)])
add_table_block(story, C.BLOCKERS_TABLE, [0.19, 0.37, 0.12, 0.32],
                'Tableau 5 — État des bloqueurs production à la date de l\'audit', status_col=2)
story += h2_block('5.1 Package de production prêt', [Paragraph(C.CH5_1_P1, body)])
story.append(Paragraph(C.CH5_1_P2, body))

# ── 6. Risques et recommandations ────────────────────────────────────────────
story += h1_block('6. Risques et recommandations')
story += h2_block('6.1 Frontières et risques résiduels', [Paragraph(C.CH6_1_P1, body)])
for r in C.RISKS:
    story.append(Paragraph('•  %s' % r, bullet))
story.append(Spacer(1, 4))
story += h2_block('6.2 Recommandations priorisées', [Paragraph(C.CH6_2_P1, body)])
for i, (title, detail) in enumerate(C.RECOMMENDATIONS, start=1):
    story.append(Paragraph('<b>%d. %s.</b> %s' % (i, title, detail), bullet))
story.append(Spacer(1, 4))
story += h2_block('6.3 Verdict', [Paragraph(C.CH6_3_P1, body)])

# ── Build ─────────────────────────────────────────────────────────────────────
doc = TocDocTemplate(
    OUT, pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN,
    topMargin=MARGIN, bottomMargin=0.85 * inch,
    title=C.TITLE, author='Z.ai', creator='Z.ai',
    subject='Audit de complétude technique — plateforme YAHRIA CODE OS et livrable RUN-000019',
)
doc.multiBuild(story, onFirstPage=on_page, onLaterPages=on_page)
print('BODY OK ->', OUT)
