# -*- coding: utf-8 -*-
"""Génération du corps du rapport PDF YAHRIA (ReportLab, route Report du skill pdf).

Pipeline : corps ReportLab (TOC + 9 chapitres) → fusion couverture HTML/Playwright
via pypdf → validators (meta.brand, font.check, toc, pages.clean, pdf_qa).
"""
import os
import sys
import hashlib

PDF_SKILL_DIR = "/home/z/my-project/skills/pdf"
SCRIPTS_DIR = os.path.join(PDF_SKILL_DIR, "scripts")
if SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, SCRIPTS_DIR)
CONTENT_DIR = "/home/z/my-project/scripts"
if CONTENT_DIR not in sys.path:
    sys.path.insert(0, CONTENT_DIR)

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT, TA_CENTER
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily, stringWidth
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, PageBreak,
                                Table, TableStyle, KeepTogether, CondPageBreak,
                                Image, HRFlowable)
from reportlab.platypus.tableofcontents import TableOfContents

from report_content import BLOCKS

# ── Fonts (allowed set only) ─────────────────────────────────────────
FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

from pdf import install_font_fallback  # noqa: E402  (skill helper)
install_font_fallback()

# ── Cascade Palette (auto-generated by design_engine.py palette-cascade) ──
PAGE_BG       = colors.HexColor('#f5f5f4')
SECTION_BG    = colors.HexColor('#f2f1f0')
CARD_BG       = colors.HexColor('#ebeae8')
TABLE_STRIPE  = colors.HexColor('#ededeb')
HEADER_FILL   = colors.HexColor('#4e4732')
COVER_BLOCK   = colors.HexColor('#746c56')
BORDER        = colors.HexColor('#c5bfac')
ICON          = colors.HexColor('#a48e4b')
ACCENT        = colors.HexColor('#92761f')
ACCENT_2      = colors.HexColor('#3aa0c2')
TEXT_PRIMARY  = colors.HexColor('#151513')
TEXT_MUTED    = colors.HexColor('#7e7c74')
SEM_ERROR     = colors.HexColor('#a25b54')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ── Page geometry (symmetric margins) ────────────────────────────────
MARGIN = 1.0 * inch
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN
H1_THRESHOLD = AVAIL_H * 0.25

DOC_TITLE = "YAHRIA — Rapport d'analyse complet du corpus constitutionnel"
OUT_BODY = "/home/z/my-project/scripts/report_body.pdf"
OUT_FINAL = "/home/z/my-project/download/YAHRIA_Rapport_Analyse_Complet.pdf"
COVER_PDF = "/home/z/my-project/scripts/report_cover.pdf"
CHART_PNG = "/home/z/my-project/scripts/report_chart_dims.png"

# ── Styles ───────────────────────────────────────────────────────────
body_style = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5, leading=17,
                            alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY,
                            spaceBefore=0, spaceAfter=12)
h1_style = ParagraphStyle('H1', fontName='FreeSerif', fontSize=20, leading=26,
                          alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                          spaceBefore=22, spaceAfter=4)
h2_style = ParagraphStyle('H2', fontName='FreeSerif', fontSize=14, leading=20,
                          alignment=TA_LEFT, textColor=HEADER_FILL,
                          spaceBefore=16, spaceAfter=8)
bullet_style = ParagraphStyle('Bullet', parent=body_style, leftIndent=18,
                              firstLineIndent=0, bulletIndent=4, spaceAfter=8)
caption_style = ParagraphStyle('Caption', fontName='FreeSerif', fontSize=8.5,
                               leading=12, alignment=TA_CENTER, textColor=TEXT_MUTED,
                               spaceBefore=3, spaceAfter=6)
cell_style = ParagraphStyle('Cell', fontName='FreeSerif', fontSize=9, leading=12.5,
                            alignment=TA_LEFT, textColor=TEXT_PRIMARY, wordWrap='CJK')
cell_center = ParagraphStyle('CellC', parent=cell_style, alignment=TA_CENTER)
cell_header = ParagraphStyle('CellH', fontName='FreeSerif', fontSize=9.5, leading=12.5,
                             alignment=TA_CENTER, textColor=colors.white)
toc_title_style = ParagraphStyle('TocTitle', fontName='FreeSerif', fontSize=18,
                                 leading=24, textColor=TEXT_PRIMARY, spaceAfter=16)
stat_style = ParagraphStyle('StatBig', fontName='FreeSerif', fontSize=19, leading=23,
                            textColor=ACCENT, alignment=TA_CENTER)
stat_label_style = ParagraphStyle('StatLabel', fontName='FreeSerif', fontSize=8,
                                  leading=11, textColor=TEXT_MUTED, alignment=TA_CENTER)


class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            # Displayed body numbering = physical page - 1 (TOC page is roman i)
            self.notify('TOCEntry', (level, text, self.page - 1, key))


def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


MAX_KEEP_HEIGHT = A4[1] * 0.4

def safe_keep_together(elements):
    total_h = 0
    for el in elements:
        try:
            _, h = el.wrap(AVAIL_W, AVAIL_H)
        except Exception:
            h = 0
        total_h += h
    if total_h <= MAX_KEEP_HEIGHT:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)


def make_table(spec):
    headers = spec['headers']
    rows = spec['rows']
    ratios = spec['ratios']
    aligns = spec.get('aligns', ['left'] * len(headers))
    col_widths = [r * AVAIL_W * 0.98 for r in ratios]
    assert sum(col_widths) <= AVAIL_W + 0.5, "table overflow"
    data = [[Paragraph('<b>%s</b>' % h, cell_header) for h in headers]]
    for row in rows:
        cells = []
        for i, val in enumerate(row):
            st = cell_center if aligns[i] == 'center' else cell_style
            cells.append(Paragraph(str(val), st))
        data.append(cells)
    tbl = Table(data, colWidths=col_widths, hAlign='CENTER', repeatRows=1)
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for ri in range(1, len(data)):
        style_cmds.append(('BACKGROUND', (0, ri), (-1, ri),
                           TABLE_ROW_EVEN if ri % 2 == 1 else TABLE_ROW_ODD))
    tbl.setStyle(TableStyle(style_cmds))
    flow = [Spacer(1, 18)]
    _, th = tbl.wrap(AVAIL_W, AVAIL_H)
    if th <= MAX_KEEP_HEIGHT:
        flow.append(KeepTogether([tbl]))
    else:
        flow.append(tbl)
    flow.append(Spacer(1, 6))
    flow.append(Paragraph(spec['caption'], caption_style))
    flow.append(Spacer(1, 12))
    return flow, th


def make_callout(stats):
    n = len(stats)
    gap = 12
    box_w = (AVAIL_W * 0.98 - gap * (n - 1)) / n
    col_widths, val_row, lab_row = [], [], []
    for idx, (value, label) in enumerate(stats):
        col_widths.append(box_w)
        val_row.append(Paragraph('<b>%s</b>' % value, stat_style))
        lab_row.append(Paragraph(label, stat_label_style))
        if idx < n - 1:
            col_widths.append(gap)
            val_row.append('')
            lab_row.append('')
    row = Table([val_row, lab_row], colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, 0), 9),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 2),
        ('TOPPADDING', (0, 1), (-1, 1), 2),
        ('BOTTOMPADDING', (0, 1), (-1, 1), 9),
        ('LEFTPADDING', (0, 0), (-1, -1), 2),
        ('RIGHTPADDING', (0, 0), (-1, -1), 2),
    ]
    for k in range(n):
        c = k * 2
        style_cmds.append(('BACKGROUND', (c, 0), (c, 1), CARD_BG))
    # Single enclosing frame + internal vertical dividers → one symmetric block
    style_cmds.append(('BOX', (0, 0), (-1, 1), 1, ACCENT))
    for k in range(n - 1):
        c = k * 2 + 1
        style_cmds.append(('LINEBEFORE', (c, 0), (c, 1), 1, ACCENT))
    row.setStyle(TableStyle(style_cmds))
    return [Spacer(1, 10), KeepTogether([row]), Spacer(1, 14)]


def make_chart(spec):
    from PIL import Image as PILImage
    pil = PILImage.open(spec['path'])
    ow, oh = pil.size
    max_w, max_h = AVAIL_W * 0.96, 290
    ratio = min(max_w / ow if ow > max_w else 1.0, max_h / oh if oh > max_h else 1.0)
    img = Image(spec['path'], width=ow * ratio, height=oh * ratio)
    out = safe_keep_together([img, Paragraph(spec['caption'], caption_style)])
    return [Spacer(1, 16)] + out + [Spacer(1, 14)]


def table_height_estimate(spec):
    ratios = spec['ratios']
    col_widths = [r * AVAIL_W * 0.98 for r in ratios]
    h = 24  # header row
    for row in spec['rows']:
        max_lines = 1
        for i, val in enumerate(row):
            w = col_widths[i] - 12
            text_w = stringWidth(str(val), 'FreeSerif', 9)
            import math
            max_lines = max(max_lines, math.ceil(text_w / max(w, 30)))
        h += max_lines * 12.5 + 10
    return h


def build_chart_png():
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.font_manager as fm
    fm.fontManager.addfont('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf')
    import matplotlib.pyplot as plt
    plt.rcParams['font.sans-serif'] = ['DejaVu Sans']
    plt.rcParams['axes.unicode_minus'] = False

    dims = [
        ("Vision doctrinale", 5),
        ("Gouvernance & preuves", 5),
        ("Sécurité & confinement", 4),
        ("Architecture cognitive", 3),
        ("Cohérence interne", 3),
        ("Exécutabilité", 2),
        ("Packaging & complétude", 2),
    ]
    score_color = {5: '#4e4732', 4: '#746c56', 3: '#92761f', 2: '#c5bfac'}
    labels = [d[0] for d in dims][::-1]
    values = [d[1] for d in dims][::-1]
    bar_colors = [score_color[v] for v in values]

    fig, ax = plt.subplots(figsize=(7.4, 3.5), constrained_layout=True)
    bars = ax.barh(labels, values, color=bar_colors, height=0.62, edgecolor='none')
    for sp in ('top', 'right'):
        ax.spines[sp].set_visible(False)
    ax.spines['left'].set_color('#c5bfac')
    ax.spines['bottom'].set_color('#c5bfac')
    ax.set_xlim(0, 5.4)
    ax.set_xticks([0, 1, 2, 3, 4, 5])
    ax.grid(axis='x', linestyle='--', alpha=0.2, linewidth=0.5)
    ax.set_axisbelow(True)
    ax.tick_params(axis='both', labelsize=10, colors='#151513', length=0)
    for bar, v in zip(bars, values):
        ax.text(v + 0.08, bar.get_y() + bar.get_height() / 2, f"{v}/5",
                va='center', ha='left', fontsize=10, color='#151513')
    fig.savefig(CHART_PNG, dpi=200, facecolor='white')
    plt.close(fig)


def render_flowables():
    story = []
    # ── TOC (front matter, roman i) ──
    story.append(Paragraph('<b>Table des matières</b>', toc_title_style))
    toc = TableOfContents()
    toc.levelStyles = [
        ParagraphStyle('TOC0', fontName='FreeSerif', fontSize=11.5, leading=20,
                       leftIndent=6, textColor=TEXT_PRIMARY),
        ParagraphStyle('TOC1', fontName='FreeSerif', fontSize=10.5, leading=17,
                       leftIndent=26, textColor=TEXT_MUTED),
    ]
    story.append(toc)
    story.append(PageBreak())  # structural break: TOC → content

    i = 0
    n = len(BLOCKS)
    while i < n:
        block = BLOCKS[i]
        t = block[0]
        if t in ('h1', 'h2'):
            level = 0 if t == 'h1' else 1
            style = h1_style if t == 'h1' else h2_style
            heading = add_heading(block[1], style, level=level)
            rule = HRFlowable(width='100%', thickness=1.2 if t == 'h1' else 0.8,
                              color=ACCENT if t == 'h1' else BORDER,
                              spaceBefore=0, spaceAfter=10 if t == 'h1' else 8)
            # Look-ahead: require room for heading + next table/chart
            required = 90
            if i + 1 < n and BLOCKS[i + 1][0] == 'table':
                required = 70 + table_height_estimate(BLOCKS[i + 1][1]) + 40
            story.append(CondPageBreak(min(required, AVAIL_H * 0.92)))
            story.extend(safe_keep_together([heading, rule]))
            i += 1
            continue
        if t == 'body':
            story.append(Paragraph(block[1], body_style))
        elif t == 'num':
            for k, item in enumerate(block[1], 1):
                story.append(Paragraph('<b>%d.</b>  %s' % (k, item), bullet_style))
            story.append(Spacer(1, 6))
        elif t == 'table':
            flow, _ = make_table(block[1])
            story.extend(flow)
        elif t == 'callout':
            story.extend(make_callout(block[1]['stats']))
        elif t == 'chart':
            block[1]['path'] = os.path.join(CONTENT_DIR, block[1]['path'])
            story.extend(make_chart(block[1]))
        i += 1
    return story


def on_page(canvas, doc):
    canvas.saveState()
    # header: title left + accent rule
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 40, DOC_TITLE)
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 46, PAGE_W - MARGIN, PAGE_H - 46)
    # footer: light rule + author left + page number right
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 44, PAGE_W - MARGIN, 44)
    canvas.setFont('FreeSerif', 7.5)
    canvas.drawString(MARGIN, 32, 'assihervey-coder · YAHRIA CODE OS')
    page_label = 'i' if doc.page == 1 else str(doc.page - 1)
    canvas.drawRightString(PAGE_W - MARGIN, 32, page_label)
    canvas.restoreState()


def main():
    build_chart_png()
    doc = TocDocTemplate(
        OUT_BODY, pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN, topMargin=64, bottomMargin=64,
        title=DOC_TITLE, author='Z.ai', creator='Z.ai',
        subject="Analyse constitutionnelle du corpus YAHRIA — forces, défauts, évaluation et corrections",
    )
    story = render_flowables()
    doc.multiBuild(story, onFirstPage=on_page, onLaterPages=on_page)
    print("body OK:", OUT_BODY)

    # ── Merge cover as page 0 ──
    from pypdf import PdfReader, PdfWriter
    A4_W, A4_H = 595.28, 841.89

    def normalize(page):
        w, h = float(page.mediabox.width), float(page.mediabox.height)
        if abs(w - A4_W) > 0.1 or abs(h - A4_H) > 0.1:
            page.scale_to(A4_W, A4_H)
        return page

    writer = PdfWriter()
    writer.add_page(normalize(PdfReader(COVER_PDF).pages[0]))
    for page in PdfReader(OUT_BODY).pages:
        writer.add_page(normalize(page))
    writer.add_metadata({
        '/Title': DOC_TITLE, '/Author': 'Z.ai', '/Creator': 'Z.ai',
        '/Subject': "Analyse constitutionnelle du corpus YAHRIA — forces, défauts, évaluation et corrections",
    })
    os.makedirs(os.path.dirname(OUT_FINAL), exist_ok=True)
    with open(OUT_FINAL, 'wb') as f:
        writer.write(f)
    print("final OK:", OUT_FINAL)


if __name__ == '__main__':
    main()
